dds_project/dds_project/urls.py
from django.contrib import admin
from django.urls import path

from dds.views import *
from ddsBD.views import *

urlpatterns = [
    #основные страницы
    path("admin/", admin.site.urls),
    path('',index, name='index'),
    #создание
    path('create/',create, name='create'),
    path('success/', success_view, name='success_url'),
    #редактирование
    path('edit_dds/<int:id>/', edit_dds, name='edit_dds'),
    #словарь
    path('guide/',guide,name='guide'),

    #для сохраниния, словари
    path('save_status/', save_status, name='save_status'),
    path('save_type/', save_type, name='save_type'),
    path('save_category/', save_category, name='save_category'),
    path('save_subcategory/', save_subcategory, name='save_subcategory'),
    #для изменения, словари
    path('update_status/<int:status_id>/', update_status, name='update_status'),
    path('update_type/<int:type_id>/', update_type, name='update_stype'),
    path('update_category/', update_category, name='update_category'),
    path('update_subcategory/', update_subcategory, name='update_subcategory'),
    #для удаления, словари
    path('delete_status/<int:status_id>/', delete_status, name='delete_status'),
    path('delete_type/<int:type_id>/', delete_type, name='delete_type'),
    path('delete_category/<int:category_id>/', delete_category, name='delete_category'),
    path('delete_subcategory/<int:subcategory_id>/', delete_subcategory, name='delete_subcategory'),


    #для получения списков категорий и подкатегорий
    path('get_categories/', get_categories, name='get_categories'),
    path('get_subcategories/', get_subcategories, name='get_subcategories'),
    # Удаление записи ддс
    path('delete_dds/<int:id>/', delete_dds, name='delete_dds'),
]

dds_project/dds/models.py
from django.db import models
from ddsBD.models import *
from django.core.validators import MinValueValidator


# класс выводимой информации  
class DDS(models.Model):
    created_at = models.DateField(verbose_name="Дата создания записи")
    #так как в тз не сказано, что поле статус необязательно к заполнению, тогда пускай будет обязательно
    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name="Статус")
    typedds = models.ForeignKey(Type,on_delete=models.CASCADE, blank=False, null=False, verbose_name="Тип")
    category=models.ForeignKey(Category, on_delete=models.CASCADE, blank=False, null=False, verbose_name="Категория")
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=False, null=False, verbose_name="Подкатегория")
    summa=models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        blank=False, 
        null=False,
        validators=[MinValueValidator(0.01)],
        verbose_name="Сумма")
    comment = models.TextField(blank=True, null=True, verbose_name="Комментарий")

    class Meta:
        verbose_name = "Данные о движении денежных средств"
        verbose_name_plural = "Даннные о движениях денежных средств"

dds_project/dds/forms.py
from django import forms
from .models import DDS
from ddsBD.models import *
import datetime

class DDSForm(forms.ModelForm):
    class Meta:
        model = DDS
        fields = ['created_at', 'status', 'typedds', 'comment', 'category', 'subcategory', 'summa']
        widgets = {
            'created_at': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите комментарий'}),
            'summa': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '5000'}),
        }


    def clean_created_at(self):
        created_at = self.cleaned_data['created_at']
        if created_at > datetime.date.today():
            raise forms.ValidationError("Дата не может быть в будущем.")
        return created_at

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount < 0:
            raise forms.ValidationError("Сумма должна быть положительной.")
        return amount

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].queryset = Status.objects.all()
        self.fields['typedds'].queryset = Type.objects.all()

class DDSEditForm(forms.ModelForm):
    class Meta:
        model = DDS
        fields = ['created_at', 'status', 'typedds', 'comment', 'category', 'subcategory', 'summa']

    widgets = {
        'created_at': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        'status': forms.Select(attrs={'class': 'form-control'}),
        'typedds': forms.Select(attrs={'class': 'form-control'}),
        'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите комментарий'}),
        'category': forms.Select(attrs={'class': 'form-control'}),
        'subcategory': forms.Select(attrs={'class': 'form-control'}),
        'summa': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '5000'}),
    }

dds_project/dds/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import DDS 
from ddsBD.models import *
from .forms import DDSForm, DDSEditForm
import datetime
from django.views.decorators.http import require_POST
import logging

#обработка удаления
@require_POST
def delete_dds(request, id):
    try:
        dds = get_object_or_404(DDS, id=id)
        dds.delete()
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})
    
# Настройка логгера
logger = logging.getLogger(__name__)
#функции для получения категорий и подкатегорий для списка
def get_categories(request):
    typedds_id = request.GET.get('typedds_id')
    categories = Category.objects.filter(typedds_id=typedds_id).values('id', 'name')
    return JsonResponse(list(categories), safe=False)

def get_subcategories(request):
    category_id = request.GET.get('category_id')
    subcategories = SubCategory.objects.filter(category_id=category_id).values('id', 'name')
    return JsonResponse(list(subcategories), safe=False)

#отображения страниц и некоторые действия№№№№№№№№№№№№№ 
def index(request):

    #Получаем данные
    dds_data = DDS.objects.all()

    # Данные для фильтрации
    status_data = Status.objects.all()
    type_data = Type.objects.all()
    category_data = Category.objects.all()
    subcategory_data = SubCategory.objects.all()

    # Получаем параметры фильтрации из GET-запроса
    date_from = request.GET.get('date_from')
    date_to = request.GET.get('date_to')
    status = request.GET.get('status')
    type_dds = request.GET.get('type')
    category = request.GET.get('category')
    subcategory = request.GET.get('subcategory')

    if date_from:
        dds_data = dds_data.filter(created_at__gte=date_from)
    if date_to:
        dds_data = dds_data.filter(created_at__lte=date_to)
    if status:
        dds_data = dds_data.filter(status__name=status)
    if type_dds:
        dds_data = dds_data.filter(typedds__name=type_dds)
    if category:
        dds_data = dds_data.filter(category__name=category)
    if subcategory:
        dds_data = dds_data.filter(subcategory__name=subcategory)
    

    context = {
        'dds_data': dds_data,
        'status_data': status_data,
        'type_data': type_data,
        'category_data': category_data,
        'subcategory_data': subcategory_data,  
    }

    return render(request, 'index.html', context)

#страница создания записи ддс
def create(request):
    status_data = Status.objects.all()
    type_data = Type.objects.all()
    category_data = Category.objects.all()
    subcategory_data = SubCategory.objects.all()

    if request.method == 'POST':
        form = DDSForm(request.POST)
        if form.is_valid():
            # Доп валидация
            created_at = form.cleaned_data['created_at']
            if created_at > datetime.date.today():
                form.add_error('created_at', "Дата не может быть в будущем")
            else:
                form.save()
                return redirect('success_url')
    else:
        form = DDSForm(initial={'created_at': datetime.date.today()})

    context = {
        'status_data': status_data,
        'type_data': type_data,
        'category_data': category_data,
        'subcategory_data': subcategory_data,
        'form': form,
    }
    return render(request, 'create.html', context)

#страница редактирования
def edit_dds(request, id):
    
    dds_entry = get_object_or_404(DDS, id=id)

    if request.method == 'POST':
        # Если данные отправлены, обновляем запись
        form = DDSEditForm(request.POST, instance=dds_entry)
        if form.is_valid():
            form.save()
            return redirect('index')  
    else:
        # Если запрос GET, отображаем форму с текущими данными
        form = DDSEditForm(instance=dds_entry)
    return render(request,'edit.html',{'form': form})

#Страница успеха
def success_view(request):
    return render(request, 'success.html')

dds_project/dds/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My company - создание записи ДДС</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
</head>
<body>
<!--Шапка-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">My company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
            <!--Ссылка на справочник-->
            <a href="{% url 'guide' %}" class="btn btn-outline-info mr-2" role="button">Справочник</a>
        </div>
    </nav>

<!--Блок создания записи-->
    <section class="container mt-4">
        <h1>Создать запись о ДДС</h1>
        <!--Блок с формами-->
        <div class="mt-4">
            <div class="row">
                <div class="col-md-6">
                    <form method="post">
                        {% csrf_token %}
                        <!-- Поле "Дата" -->
                        <div class="form-group">
                            <label for="id_created_at">Дата</label>
                            {{ form.created_at }}
                            <!--<input type="date" class="form-control" id="id_created_at" name="created_at" value="{{ form.created_at.value|default:'' }}">-->
                        </div>
        
                        <!-- Поле "Статус" -->
                        <div class="form-group">
                            <label for="id_status">Статус</label>
                            {{ form.status }}
                        </div>
        
                        <!-- Поле "Тип" -->
                        <div class="form-group">
                            <label for="id_typedds">Тип</label>
                            {{ form.typedds }}
                        </div>
        
                        <!-- Поле "Комментарий" -->
                        <div class="form-group d-flex flex-column">
                            <label for="id_comment">Комментарий</label>
                            <textarea class="form-control flex-grow-1" id="id_comment" name="comment" placeholder="Введите комментарий">{{ form.comment.value|default:'' }}</textarea>
                        </div>
                </div>
                <div class="col-md-6 d-flex flex-column">
                    <!-- Поле "Категория" -->
                    <div class="form-group">
                        <label for="id_category">Категория</label>
                        {{ form.category }}
                    </div>
        
                    <!-- Поле "Подкатегория" -->
                    <div class="form-group">
                        <label for="id_subcategory">Подкатегория</label>
                        {{ form.subcategory }}
                    </div>
        
                    <!-- Поле "Сумма" с кастомными стилями -->
                    <div class="form-group">
                        <label for="id_summa">Сумма</label>
                        <input type="text" class="form-control summa-input" id="id_summa" name="summa" placeholder="5000" value="{{ form.summa.value|default:'' }}">
                        <span class="error-message" style="color: red; display: none;">Введите корректное значение, например 5000</span>
                    </div>
        
                    <!-- Кнопка "Создать запись" -->
                    <div class="form-group flex-grow-1 d-flex justify-content-center align-items-center">
                        <button type="submit" class="btn btn-outline-info">Создать запись</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        
        
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/logic_choice/create_logic.js'%}"></script>
    <script src ="{% static 'js/validate/validatoe.js' %}"></script>
</body>
</html>

dds_project/dds/templates/dds_table.html
{% load static %}
<meta name="csrf-token" content="{{ csrf_token }}">

<div id="dds-table">
    <table class="table">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Статус</th>
                <th>Тип</th>
                <th>Категория</th>
                <th>Подкатегория</th>
                <th>Сумма</th>
                <th>Комментарий</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for dds in dds_data %}
            <tr data-id="{{ dds.id }}">
                <td>{{ dds.created_at }}</td>
                <td>{{ dds.status.name }}</td>
                <td>{{ dds.typedds.name }}</td>
                <td>{{ dds.category.name }}</td>
                <td>{{ dds.subcategory.name }}</td>
                <td>{{ dds.summa }}</td>
                <td>{{ dds.comment }}</td>
                <td class="btn-group">
                    <a href="{% url 'edit_dds' dds.id %}" class="btn btn-outline-info mr-2" role="button">Редактировать</a>
                    <button class="btn btn-outline-danger ml-2 delete-button">Удалить</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

dds_project/dds/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My company - редактирование записи ДДС</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
</head>
<body>
<!--Шапка-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">My company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
            <!--Ссылка на справочник-->
            <a href="{% url 'guide' %}" class="btn btn-outline-info mr-2" role="button">Справочник</a>
        </div>
    </nav>

<!--Блок создания записи-->
    <section class="container mt-4">
        <h1>Редактировать запись о ДДС</h1>
        <!--Блок с формами-->
        <div class="mt-4">
            <div class="row">
                <div class="col-md-6">
                    <form method="post">
                        {% csrf_token %}
                        <!-- Поле "Дата" -->
                        <div class="form-group">
                            <label for="id_created_at">Дата</label>
                            <input type="date" class="form-control" id="id_created_at" name="created_at" value="{{ form.created_at.value|default:''|date:'Y-m-d' }}">
                        </div>
        
                        <!-- Поле "Статус" -->
                        <div class="form-group">
                            <label for="id_status">Статус</label>
                            {{ form.status }}
                        </div>
        
                        <!-- Поле "Тип" -->
                        <div class="form-group">
                            <label for="id_typedds">Тип</label>
                            {{ form.typedds }}
                        </div>
        
                        <!-- Поле "Комментарий" -->
                        <div class="form-group d-flex flex-column">
                            <label for="id_comment">Комментарий</label>
                            <textarea class="form-control flex-grow-1" id="id_comment" name="comment" placeholder="Введите комментарий">{{ form.comment.value|default:'' }}</textarea>
                        </div>
                </div>
                <div class="col-md-6 d-flex flex-column">
                    <!-- Поле "Категория" -->
                    <div class="form-group">
                        <label for="id_category">Категория</label>
                        {{ form.category }}
                    </div>
        
                    <!-- Поле "Подкатегория" -->
                    <div class="form-group">
                        <label for="id_subcategory">Подкатегория</label>
                        {{ form.subcategory }}
                    </div>
        
                    <!-- Поле "Сумма" с кастомными стилями -->
                    <div class="form-group">
                        <label for="id_summa">Сумма</label>
                        <input type="text" class="form-control" id="id_summa" name="summa" placeholder="5000" value="{{ form.summa.value|default:'' }}">
                    </div>
        
                    <!-- Кнопка "Создать запись" -->
                    <div class="form-group flex-grow-1 d-flex justify-content-center align-items-center">
                        <button type="submit" class="btn btn-outline-info">Редактировать запись</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        
        
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/logic_choice/create_logic.js'%}"></script>
    <script src ="{% static 'js/validate/validatoe.js' %}"></script>
</body>
</html>

dds_project/dds/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My company - движение денежных средств</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel = "stylesheet" href = "{% static 'css/main.css' %}">
    </head>
<body>
    <!--Верхняя шапка-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">My company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
            <!--Cсылка на добавление записи-->
            <a href="{% url 'create'%}" class="btn btn-outline-info mr-2" role="button">Создать запись</a>
            <!--Ссылка на справочник-->
            <a href="{% url 'guide' %}" class="btn btn-outline-info mr-2" role="button">Справочник</a>
        </div>

    </nav>
<!--Секция организации под шапкой-->
<section class="event-header">
    <div class="event-header-content">
      <h1>MY COMPANY</h1>
      <div class="event-info">
          <i class="fas fa-calendar-alt"></i> 2021-2025
      </div>
      <div class="event-info">
          <i class="fas fa-map-marker-alt"></i> г. Москва ул. 3-я Строителей д. 25
      </div>
    </div>
  </section>


<!--Секция с фильтром-->
<section class="search-bar container center">
    <div class="row">
        <div class="col-md-12">
        <form id="filter-form" method="get" action="">
            
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="date_from">Дата (с):</label>
                                <input type="date" class="form-control" id="date_from" name="date_from">
                            </div>
                            <div class="col-md-6">
                                <label for="date_to">Дата (по):</label>
                                <input type="date" class="form-control" id="date_to" name="date_to">
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-2">
                        <label for="status">Статус:</label>
                        <select class="form-control" id="status" name="status">
                            <option value="">Все</option>
                            {% for status in status_data %}
                            <option value="{{ status.name }}">{{ status.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label for="type">Тип:</label>
                        <select class="form-control" id="type" name="type">
                            <option value="">Все</option>
                            {% for typedds in type_data %}
                            <option value="{{ typedds.name }}">{{ typedds.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label for="category">Категория:</label>
                        <select class="form-control" id="category" name="category">
                            <option value="">Все</option>
                            {% for category in category_data %}
                            <option value="{{ category.name }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label for="subcategory">Подкатегория:</label>
                        <select class="form-control" id="subcategory" name="subcategory">
                            <option value="">Все</option>
                            {% for subcategory in subcategory_data %}
                            <option value="{{ subcategory.name }}">{{ subcategory.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row mt-2 justify-content-center">
                    <h2 style="font-size: 1rem; color: #17A2C8;">Пожалуйста, выберите, какие данные хотите увидеть</n2>
                </div>
                <div class="row mt-2 justify-content-center">
                    <div class="col-md-2">
                        <button type="submit" id="filter-button" class="btn btn-outline-info">Отфильтровать</button>
                    </div>
                </div>
            
        </form>
    </div>
    </div>
</section>

<!--Заголовок-->
    <section class="text-center">
        <h2>Данные о движении денежных средств</h2>
    </section>
    
<!--Секция таблицы-->
<section class="container mt-4">
    <div class="table-responsive">
        {% include 'dds_table.html' %}
    </div>
</section>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/dds_table_filter.js'%}"> </script>
    <script src="{% static 'js/delete_dds.js'%}"> </script>
</body>
</html>

dds_project/dds/templates/success.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My company - успешное создание</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <style>
        .center-block {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh; /* Высота блока, чтобы он был по центру страницы */
            flex-direction: column;
        }
        .success-message {
            color: green; /* Зеленый цвет текста */
            font-size: 1.5rem; /* Размер текста */
            font-weight: 400; /* Меньшая жирность текста */
            margin-bottom: 20px; /* Отступ снизу */
        }
    </style>
    
</head>
<body>
<!--Шапка-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">My company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
            <!--Ссылка на справочник-->
            <a href="{% url 'guide' %}" class="btn btn-outline-info mr-2" role="button">Справочник</a>
        </div>
    </nav>

    <!-- Центрированный блок с сообщением и кнопкой -->
    <section class="center-block">
        <h1 class="success-message">Запись успешно создана!</h1>
        <!-- Ссылка на добавление записи -->
        <a href="{% url 'create' %}" class="btn btn-outline-info" role="button">Создать новую запись</a>
    </section>

</body>
</html>